### PR TITLE
HTML template correction

### PR DESCRIPTION
**Pull request by valentineus**
CHANGELOG
* Fixed the HTML template. Now it's valid HTML5. And it is perfectly displayed on mobile devices.
* Added reset styles for CSS. Parasitic artifacts have disappeared.

Before

After

### CODE REVIEW

**Comment by valentineus** [comment]
@aprosvetova Yep! I'll do.

**Comment by valentineus** [comment]
@aprosvetova 
Do I understand correctly that centering is needed on mobile devices?

Desktop:


Mobile:

**Comment by aprosvetova** [comment]
I personally hate the way the feed widget works now, I mean this little scrollable block. It's made this way because I suck at frontend, I can't design and make up a page. Please let me know if you have better ideas.

**Comment by valentineus** [comment]
@aprosvetova 
> On all devices. This is how it looks now on desktop:

I understood. Done.

**Comment by aprosvetova** [comment]
Thank you for your fixes, I will try them out locally and merge.

Some food for thought:
image

I think this page could look better if the feed (blue block) took all available space in the bottom, while the main block (red one) always stays centered, even when the feed is scrolled. I have no idea how to achieve that tho :<

**Pull request closed without merging**
